import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import {
  Anchor,
  IconButton,
  Interactive,
  RiCommandIcon,
  RiSunIcon,
  Surface,
  Text,
  ThemeProvider,
  View,
} from "natmfat";
import { tokens } from "natmfat/lib/tokens";
import Link from "next/link";
import { Section } from "./components/Section";
import { ThemeButton } from "./components/ThemeButton";
import { Logo } from "./components/Logo";

const fontMono = IBM_Plex_Mono({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-family-code",
});

const fontSans = IBM_Plex_Sans({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-family-default",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.className} ${fontMono.className} antialiased`}
        data-theme="dark"
      >
        <ThemeProvider>
          <header className="flex border-b border-interactive border-dashed fixed left-0 right-0 top-0 bg-surface z-50 w-full">
            <View className="px-6 py-4 border-x border-interactive border-dashed max-w-7xl w-full mx-auto flex-row justify-between items-center">
              <View asChild>
                <nav className="flex-row items-center gap-4">
                  <View className="flex-row items-center gap-2" asChild>
                    <Link href="/">
                      <Logo />
                      <Text className="text-subhead-default font-bold">
                        natmfat/ui
                      </Text>
                    </Link>
                  </View>
                  <Link href="/docs">Docs</Link>
                  <Link href="/docs/components/accordion">Components</Link>
                  <Link href="/themes">Themes</Link>
                  <Link href="/magic">Magic</Link>
                </nav>
              </View>

              <View className="flex-row items-center gap-2">
                <Interactive>
                  <View className="h-8 select-none flex-row text-foreground-dimmest hover:text-foreground-dimmer items-center justify-between gap-2 w-64 max-w-full shrink-1 px-1">
                    <Text className="pl-2">Search documentation...</Text>

                    <Surface
                      elevated
                      className="flex-row items-center gap-1 text-small border border-interactive rounded-lg px-0.5"
                    >
                      <RiCommandIcon size={tokens.space12} />K
                    </Surface>
                  </View>
                </Interactive>
                <ThemeButton />
              </View>
            </View>
          </header>

          <View className="items-stretch min-h-screen">
            <View className="pt-16 flex-1 h-full">{children}</View>

            <Section>
              <footer>
                Built by{" "}
                <Anchor
                  href="https://natmfat.com"
                  target="_blank"
                  rel="noreferrer"
                >
                  natmfat
                </Anchor>
              </footer>
            </Section>
          </View>
        </ThemeProvider>
      </body>
    </html>
  );
}
